[project]
name = "kanaktanwar-tech"
version = "1.0.0"
description = "My Personal Portfolio"
authors = [
    {name = "Kanak Tanwar",email = "kanaktanwarpro@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit (>=1.42.2,<2.0.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "pre-commit (>=4.1.0,<5.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "isort (>=6.0.1,<7.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
